#! /bin/sh
compton -b --config ~/.config/compton.conf &
sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         1
bspc config window_gap          15
bspc config active_border_color '#FFFF00'
bspc confIG normal_border_color '#FFFFFF'
bspc confIG normal_border_color '#000000'


bspc config top_padding 30
bspc config bottom_padding 42
bspc config left_padding 0
bspc config right_padding 0

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Xfce4-appfinder state=floating
bspc rule -a Blueberry.py state=floating
bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium-browser desktop='^5' 
bspc rule -a vlc desktop='^9' follow=on 
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
